env: production
description: "Reaches deeper than the darkness."
author: initAlishan
keywords: [Programmer, Linux]

homeInfoParams:
 Title: initAlishan
 Content: Hello, welcome to [initAlishan](/)'s blog. I'm so serious about my blogs, I hope you'll also read them seriously. Here you'll find blogs and guides written by me. If you want to know about any specific topic then you can search for it.

defaultTheme: dark
ShowReadingTime: false
ShowCodeCopyButtons: true
showtoc: true
ShowPostNavLinks: true
ShowShareButtons: true
disableScrollToTop: true
ShowWordCount: false
ShowFullTextinRSS: true

sitemap:
 changeFreq: "hourly"
 disable: false
 filename: sitemap.xml
 priority: -1

social: true
socialIcons:
  - name: "github"
    url: "https://github.com/"
  - name: "telegram"
    url: "https://t.me"
  - name: "rss"
    url: "/rss.xml"

label:
  text: " "
  icon: /logo/initAlishan.png
  iconHeight: 40

assets:
  disableFingerprinting: true
  favicon: "/favicon/favicon.ico"
  favicon16x16: "/favicon/favicon-16x16.png"
  favicon32x32: "/favicon/favicon-32x32.png"
  apple_touch_icon: "/favicon/apple-touch-icon.png"

cover:
  hidden: true
  hiddenInSingle: true
  relative: false
  responsiveImages: true